openapi: 3.0.0

info:
  title: ServiceNow API
  version: 0.1.9
  description: We are creating swagger doc file
servers: 
   - url: http://localhost:9090/
  
   - url: http://localhost:9430/

paths:
   /list:
     get:
       summary: Return a list of Records
       description: calling the req from service now instance
       responses:
         '200':
            description: A JSON array of user names
            content:
               application/json:
                 schema:
                   type: string
                   items:
                     type: string

             
   /list/{id}:
     get:
       summary: return single list
       description: return the single record
       parameters: 
         - in: path
           name: id
           required: true
           schema:
              type: string
              
           
       responses:
        '200':
          description: record data
          content:
           application/json:
              schema:
                type: object
                properties:
                  result:
                    type: string
                  
        '404':
          description: chek with the url
        default:
          description: unexpected error
                
          
         
